// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: pb/battle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Potions       int32                  `protobuf:"varint,8,opt,name=potions,proto3" json:"potions,omitempty"`
	Treasures     int32                  `protobuf:"varint,9,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Kills         int32                  `protobuf:"varint,10,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,11,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Victories     int32                  `protobuf:"varint,12,opt,name=victories,proto3" json:"victories,omitempty"`
	Alive         bool                   `protobuf:"varint,13,opt,name=alive,proto3" json:"alive,omitempty"`
	RespawnIn     int32                  `protobuf:"varint,14,opt,name=respawn_in,json=respawnIn,proto3" json:"respawn_in,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,15,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerView) Reset() {
	*x = PlayerView{}
	mi := &file_pb_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerView) ProtoMessage() {}

func (x *PlayerView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerView.ProtoReflect.Descriptor instead.
func (*PlayerView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerView) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerView) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *PlayerView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerView) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PlayerView) GetPotions() int32 {
	if x != nil {
		return x.Potions
	}
	return 0
}

func (x *PlayerView) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *PlayerView) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerView) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerView) GetVictories() int32 {
	if x != nil {
		return x.Victories
	}
	return 0
}

func (x *PlayerView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PlayerView) GetRespawnIn() int32 {
	if x != nil {
		return x.RespawnIn
	}
	return 0
}

func (x *PlayerView) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type NPCView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Alive         bool                   `protobuf:"varint,8,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPCView) Reset() {
	*x = NPCView{}
	mi := &file_pb_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPCView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPCView) ProtoMessage() {}

func (x *NPCView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPCView.ProtoReflect.Descriptor instead.
func (*NPCView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{1}
}

func (x *NPCView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NPCView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NPCView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NPCView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NPCView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *NPCView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *NPCView) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *NPCView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type TreasureView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Value         int32                  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreasureView) Reset() {
	*x = TreasureView{}
	mi := &file_pb_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreasureView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreasureView) ProtoMessage() {}

func (x *TreasureView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreasureView.ProtoReflect.Descriptor instead.
func (*TreasureView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{2}
}

func (x *TreasureView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TreasureView) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TreasureView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TreasureView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TreasureView) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MapBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Players       int32                  `protobuf:"varint,4,opt,name=players,proto3" json:"players,omitempty"`
	Npcs          int32                  `protobuf:"varint,5,opt,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     int32                  `protobuf:"varint,6,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Primary       bool                   `protobuf:"varint,8,opt,name=primary,proto3" json:"primary,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,9,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	Checkpoint    int64                  `protobuf:"varint,10,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapBrief) Reset() {
	*x = MapBrief{}
	mi := &file_pb_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBrief) ProtoMessage() {}

func (x *MapBrief) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBrief.ProtoReflect.Descriptor instead.
func (*MapBrief) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{3}
}

func (x *MapBrief) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapBrief) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MapBrief) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *MapBrief) GetNpcs() int32 {
	if x != nil {
		return x.Npcs
	}
	return 0
}

func (x *MapBrief) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *MapBrief) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MapBrief) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *MapBrief) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *MapBrief) GetCheckpoint() int64 {
	if x != nil {
		return x.Checkpoint
	}
	return 0
}

type NodeView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	PrimaryMaps   []string               `protobuf:"bytes,4,rep,name=primary_maps,json=primaryMaps,proto3" json:"primary_maps,omitempty"`
	ReplicaMaps   []string               `protobuf:"bytes,5,rep,name=replica_maps,json=replicaMaps,proto3" json:"replica_maps,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeView) Reset() {
	*x = NodeView{}
	mi := &file_pb_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeView) ProtoMessage() {}

func (x *NodeView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeView.ProtoReflect.Descriptor instead.
func (*NodeView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{4}
}

func (x *NodeView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeView) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeView) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *NodeView) GetPrimaryMaps() []string {
	if x != nil {
		return x.PrimaryMaps
	}
	return nil
}

func (x *NodeView) GetReplicaMaps() []string {
	if x != nil {
		return x.ReplicaMaps
	}
	return nil
}

func (x *NodeView) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type MapView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Terrain       []string               `protobuf:"bytes,6,rep,name=terrain,proto3" json:"terrain,omitempty"`
	Players       []*PlayerView          `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*NPCView             `protobuf:"bytes,8,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     []*TreasureView        `protobuf:"bytes,9,rep,name=treasures,proto3" json:"treasures,omitempty"`
	Version       int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapView) Reset() {
	*x = MapView{}
	mi := &file_pb_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapView) ProtoMessage() {}

func (x *MapView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapView.ProtoReflect.Descriptor instead.
func (*MapView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{5}
}

func (x *MapView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapView) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MapView) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapView) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapView) GetTerrain() []string {
	if x != nil {
		return x.Terrain
	}
	return nil
}

func (x *MapView) GetPlayers() []*PlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MapView) GetNpcs() []*NPCView {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *MapView) GetTreasures() []*TreasureView {
	if x != nil {
		return x.Treasures
	}
	return nil
}

func (x *MapView) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BossSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossSite) Reset() {
	*x = BossSite{}
	mi := &file_pb_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossSite) ProtoMessage() {}

func (x *BossSite) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossSite.ProtoReflect.Descriptor instead.
func (*BossSite) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{6}
}

func (x *BossSite) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *BossSite) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BossSite) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BossView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,3,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Alive         bool                   `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	LastHit       string                 `protobuf:"bytes,5,opt,name=last_hit,json=lastHit,proto3" json:"last_hit,omitempty"`
	RespawnIn     int32                  `protobuf:"varint,6,opt,name=respawn_in,json=respawnIn,proto3" json:"respawn_in,omitempty"`
	AttackGap     int32                  `protobuf:"varint,7,opt,name=attack_gap,json=attackGap,proto3" json:"attack_gap,omitempty"`
	Sites         []*BossSite            `protobuf:"bytes,8,rep,name=sites,proto3" json:"sites,omitempty"`
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossView) Reset() {
	*x = BossView{}
	mi := &file_pb_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossView) ProtoMessage() {}

func (x *BossView) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossView.ProtoReflect.Descriptor instead.
func (*BossView) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BossView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BossView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *BossView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BossView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *BossView) GetLastHit() string {
	if x != nil {
		return x.LastHit
	}
	return ""
}

func (x *BossView) GetRespawnIn() int32 {
	if x != nil {
		return x.RespawnIn
	}
	return 0
}

func (x *BossView) GetAttackGap() int32 {
	if x != nil {
		return x.AttackGap
	}
	return 0
}

func (x *BossView) GetSites() []*BossSite {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *BossView) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type WorldState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Self           *PlayerView            `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Map            *MapView               `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Maps           []*MapBrief            `protobuf:"bytes,3,rep,name=maps,proto3" json:"maps,omitempty"`
	Nodes          []*NodeView            `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Boss           *BossView              `protobuf:"bytes,5,opt,name=boss,proto3" json:"boss,omitempty"`
	Events         []string               `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	SessionVersion int64                  `protobuf:"varint,7,opt,name=session_version,json=sessionVersion,proto3" json:"session_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_pb_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{8}
}

func (x *WorldState) GetSelf() *PlayerView {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *WorldState) GetMap() *MapView {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *WorldState) GetMaps() []*MapBrief {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *WorldState) GetNodes() []*NodeView {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *WorldState) GetBoss() *BossView {
	if x != nil {
		return x.Boss
	}
	return nil
}

func (x *WorldState) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WorldState) GetSessionVersion() int64 {
	if x != nil {
		return x.SessionVersion
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	MapId         string                 `protobuf:"bytes,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Confirm       string                 `protobuf:"bytes,8,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Item          string                 `protobuf:"bytes,9,opt,name=item,proto3" json:"item,omitempty"`
	Text          string                 `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	Ok            bool                   `protobuf:"varint,11,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	State         *WorldState            `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_pb_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_pb_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_pb_battle_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Message) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Message) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *Message) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Message) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *Message) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Message) GetState() *WorldState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_pb_battle_proto protoreflect.FileDescriptor

const file_pb_battle_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/battle.proto\x12\x02pb\"\xf4\x02\n" +
	"\n" +
	"PlayerView\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\a \x01(\x05R\x06attack\x12\x18\n" +
	"\apotions\x18\b \x01(\x05R\apotions\x12\x1c\n" +
	"\ttreasures\x18\t \x01(\x05R\ttreasures\x12\x14\n" +
	"\x05kills\x18\n" +
	" \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\v \x01(\x05R\x06deaths\x12\x1c\n" +
	"\tvictories\x18\f \x01(\x05R\tvictories\x12\x14\n" +
	"\x05alive\x18\r \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"respawn_in\x18\x0e \x01(\x05R\trespawnIn\x12\x1f\n" +
	"\vlast_update\x18\x0f \x01(\tR\n" +
	"lastUpdate\"\x9e\x01\n" +
	"\aNPCView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\a \x01(\x05R\x06attack\x12\x14\n" +
	"\x05alive\x18\b \x01(\bR\x05alive\"d\n" +
	"\fTreasureView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x05R\x05value\"\x86\x02\n" +
	"\bMapBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aplayers\x18\x04 \x01(\x05R\aplayers\x12\x12\n" +
	"\x04npcs\x18\x05 \x01(\x05R\x04npcs\x12\x1c\n" +
	"\ttreasures\x18\x06 \x01(\x05R\ttreasures\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x18\n" +
	"\aprimary\x18\b \x01(\bR\aprimary\x12\x1d\n" +
	"\n" +
	"is_current\x18\t \x01(\bR\tisCurrent\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\n" +
	" \x01(\x03R\n" +
	"checkpoint\"\xb5\x01\n" +
	"\bNodeView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12!\n" +
	"\fprimary_maps\x18\x04 \x03(\tR\vprimaryMaps\x12!\n" +
	"\freplica_maps\x18\x05 \x03(\tR\vreplicaMaps\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\tR\rlastHeartbeat\"\xa3\x02\n" +
	"\aMapView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x18\n" +
	"\aterrain\x18\x06 \x03(\tR\aterrain\x12(\n" +
	"\aplayers\x18\a \x03(\v2\x0e.pb.PlayerViewR\aplayers\x12\x1f\n" +
	"\x04npcs\x18\b \x03(\v2\v.pb.NPCViewR\x04npcs\x12.\n" +
	"\ttreasures\x18\t \x03(\v2\x10.pb.TreasureViewR\ttreasures\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"=\n" +
	"\bBossSite\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xf2\x01\n" +
	"\bBossView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\x05R\x05maxHp\x12\x14\n" +
	"\x05alive\x18\x04 \x01(\bR\x05alive\x12\x19\n" +
	"\blast_hit\x18\x05 \x01(\tR\alastHit\x12\x1d\n" +
	"\n" +
	"respawn_in\x18\x06 \x01(\x05R\trespawnIn\x12\x1d\n" +
	"\n" +
	"attack_gap\x18\a \x01(\x05R\tattackGap\x12\"\n" +
	"\x05sites\x18\b \x03(\v2\f.pb.BossSiteR\x05sites\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"\xf8\x01\n" +
	"\n" +
	"WorldState\x12\"\n" +
	"\x04self\x18\x01 \x01(\v2\x0e.pb.PlayerViewR\x04self\x12\x1d\n" +
	"\x03map\x18\x02 \x01(\v2\v.pb.MapViewR\x03map\x12 \n" +
	"\x04maps\x18\x03 \x03(\v2\f.pb.MapBriefR\x04maps\x12\"\n" +
	"\x05nodes\x18\x04 \x03(\v2\f.pb.NodeViewR\x05nodes\x12 \n" +
	"\x04boss\x18\x05 \x01(\v2\f.pb.BossViewR\x04boss\x12\x16\n" +
	"\x06events\x18\x06 \x03(\tR\x06events\x12'\n" +
	"\x0fsession_version\x18\a \x01(\x03R\x0esessionVersion\"\xbd\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\tR\x05mapId\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x18\n" +
	"\aconfirm\x18\b \x01(\tR\aconfirm\x12\x12\n" +
	"\x04item\x18\t \x01(\tR\x04item\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x0e\n" +
	"\x02ok\x18\v \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12$\n" +
	"\x05state\x18\r \x01(\v2\x0e.pb.WorldStateR\x05state2<\n" +
	"\x0eGatewayService\x12*\n" +
	"\n" +
	"GameStream\x12\v.pb.Message\x1a\v.pb.Message(\x010\x01B\x10Z\x0ebattleworld/pbb\x06proto3"

var (
	file_pb_battle_proto_rawDescOnce sync.Once
	file_pb_battle_proto_rawDescData []byte
)

func file_pb_battle_proto_rawDescGZIP() []byte {
	file_pb_battle_proto_rawDescOnce.Do(func() {
		file_pb_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_battle_proto_rawDesc), len(file_pb_battle_proto_rawDesc)))
	})
	return file_pb_battle_proto_rawDescData
}

var file_pb_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_battle_proto_goTypes = []any{
	(*PlayerView)(nil),   // 0: pb.PlayerView
	(*NPCView)(nil),      // 1: pb.NPCView
	(*TreasureView)(nil), // 2: pb.TreasureView
	(*MapBrief)(nil),     // 3: pb.MapBrief
	(*NodeView)(nil),     // 4: pb.NodeView
	(*MapView)(nil),      // 5: pb.MapView
	(*BossSite)(nil),     // 6: pb.BossSite
	(*BossView)(nil),     // 7: pb.BossView
	(*WorldState)(nil),   // 8: pb.WorldState
	(*Message)(nil),      // 9: pb.Message
}
var file_pb_battle_proto_depIdxs = []int32{
	0,  // 0: pb.MapView.players:type_name -> pb.PlayerView
	1,  // 1: pb.MapView.npcs:type_name -> pb.NPCView
	2,  // 2: pb.MapView.treasures:type_name -> pb.TreasureView
	6,  // 3: pb.BossView.sites:type_name -> pb.BossSite
	0,  // 4: pb.WorldState.self:type_name -> pb.PlayerView
	5,  // 5: pb.WorldState.map:type_name -> pb.MapView
	3,  // 6: pb.WorldState.maps:type_name -> pb.MapBrief
	4,  // 7: pb.WorldState.nodes:type_name -> pb.NodeView
	7,  // 8: pb.WorldState.boss:type_name -> pb.BossView
	8,  // 9: pb.Message.state:type_name -> pb.WorldState
	9,  // 10: pb.GatewayService.GameStream:input_type -> pb.Message
	9,  // 11: pb.GatewayService.GameStream:output_type -> pb.Message
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_pb_battle_proto_init() }
func file_pb_battle_proto_init() {
	if File_pb_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_battle_proto_rawDesc), len(file_pb_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_battle_proto_goTypes,
		DependencyIndexes: file_pb_battle_proto_depIdxs,
		MessageInfos:      file_pb_battle_proto_msgTypes,
	}.Build()
	File_pb_battle_proto = out.File
	file_pb_battle_proto_goTypes = nil
	file_pb_battle_proto_depIdxs = nil
}
