// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: battle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	MapId         string                 `protobuf:"bytes,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Potions       int32                  `protobuf:"varint,8,opt,name=potions,proto3" json:"potions,omitempty"`
	Treasures     int32                  `protobuf:"varint,9,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Kills         int32                  `protobuf:"varint,10,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,11,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Victories     int32                  `protobuf:"varint,12,opt,name=victories,proto3" json:"victories,omitempty"`
	Alive         bool                   `protobuf:"varint,13,opt,name=alive,proto3" json:"alive,omitempty"`
	RespawnIn     int32                  `protobuf:"varint,14,opt,name=respawn_in,json=respawnIn,proto3" json:"respawn_in,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,15,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerView) Reset() {
	*x = PlayerView{}
	mi := &file_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerView) ProtoMessage() {}

func (x *PlayerView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerView.ProtoReflect.Descriptor instead.
func (*PlayerView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerView) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PlayerView) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *PlayerView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerView) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *PlayerView) GetPotions() int32 {
	if x != nil {
		return x.Potions
	}
	return 0
}

func (x *PlayerView) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *PlayerView) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerView) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerView) GetVictories() int32 {
	if x != nil {
		return x.Victories
	}
	return 0
}

func (x *PlayerView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *PlayerView) GetRespawnIn() int32 {
	if x != nil {
		return x.RespawnIn
	}
	return 0
}

func (x *PlayerView) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

type NPCView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,7,opt,name=attack,proto3" json:"attack,omitempty"`
	Alive         bool                   `protobuf:"varint,8,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NPCView) Reset() {
	*x = NPCView{}
	mi := &file_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NPCView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NPCView) ProtoMessage() {}

func (x *NPCView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NPCView.ProtoReflect.Descriptor instead.
func (*NPCView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{1}
}

func (x *NPCView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NPCView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NPCView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NPCView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NPCView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *NPCView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *NPCView) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *NPCView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type TreasureView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Value         int32                  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreasureView) Reset() {
	*x = TreasureView{}
	mi := &file_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreasureView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreasureView) ProtoMessage() {}

func (x *TreasureView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreasureView.ProtoReflect.Descriptor instead.
func (*TreasureView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{2}
}

func (x *TreasureView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TreasureView) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TreasureView) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TreasureView) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TreasureView) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MapBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Players       int32                  `protobuf:"varint,4,opt,name=players,proto3" json:"players,omitempty"`
	Npcs          int32                  `protobuf:"varint,5,opt,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     int32                  `protobuf:"varint,6,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Primary       bool                   `protobuf:"varint,8,opt,name=primary,proto3" json:"primary,omitempty"`
	IsCurrent     bool                   `protobuf:"varint,9,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	Checkpoint    int64                  `protobuf:"varint,10,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapBrief) Reset() {
	*x = MapBrief{}
	mi := &file_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapBrief) ProtoMessage() {}

func (x *MapBrief) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapBrief.ProtoReflect.Descriptor instead.
func (*MapBrief) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{3}
}

func (x *MapBrief) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapBrief) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MapBrief) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *MapBrief) GetNpcs() int32 {
	if x != nil {
		return x.Npcs
	}
	return 0
}

func (x *MapBrief) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *MapBrief) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MapBrief) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *MapBrief) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

func (x *MapBrief) GetCheckpoint() int64 {
	if x != nil {
		return x.Checkpoint
	}
	return 0
}

type NodeView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	PrimaryMaps   []string               `protobuf:"bytes,4,rep,name=primary_maps,json=primaryMaps,proto3" json:"primary_maps,omitempty"`
	ReplicaMaps   []string               `protobuf:"bytes,5,rep,name=replica_maps,json=replicaMaps,proto3" json:"replica_maps,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeView) Reset() {
	*x = NodeView{}
	mi := &file_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeView) ProtoMessage() {}

func (x *NodeView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeView.ProtoReflect.Descriptor instead.
func (*NodeView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{4}
}

func (x *NodeView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeView) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *NodeView) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *NodeView) GetPrimaryMaps() []string {
	if x != nil {
		return x.PrimaryMaps
	}
	return nil
}

func (x *NodeView) GetReplicaMaps() []string {
	if x != nil {
		return x.ReplicaMaps
	}
	return nil
}

func (x *NodeView) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type MapView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Terrain       []string               `protobuf:"bytes,6,rep,name=terrain,proto3" json:"terrain,omitempty"`
	Players       []*PlayerView          `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*NPCView             `protobuf:"bytes,8,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     []*TreasureView        `protobuf:"bytes,9,rep,name=treasures,proto3" json:"treasures,omitempty"`
	Version       int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapView) Reset() {
	*x = MapView{}
	mi := &file_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapView) ProtoMessage() {}

func (x *MapView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapView.ProtoReflect.Descriptor instead.
func (*MapView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{5}
}

func (x *MapView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MapView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MapView) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MapView) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapView) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapView) GetTerrain() []string {
	if x != nil {
		return x.Terrain
	}
	return nil
}

func (x *MapView) GetPlayers() []*PlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MapView) GetNpcs() []*NPCView {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *MapView) GetTreasures() []*TreasureView {
	if x != nil {
		return x.Treasures
	}
	return nil
}

func (x *MapView) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BossSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossSite) Reset() {
	*x = BossSite{}
	mi := &file_battle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossSite) ProtoMessage() {}

func (x *BossSite) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossSite.ProtoReflect.Descriptor instead.
func (*BossSite) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{6}
}

func (x *BossSite) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *BossSite) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BossSite) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type BossView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Hp            int32                  `protobuf:"varint,2,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,3,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Alive         bool                   `protobuf:"varint,4,opt,name=alive,proto3" json:"alive,omitempty"`
	LastHit       string                 `protobuf:"bytes,5,opt,name=last_hit,json=lastHit,proto3" json:"last_hit,omitempty"`
	RespawnIn     int32                  `protobuf:"varint,6,opt,name=respawn_in,json=respawnIn,proto3" json:"respawn_in,omitempty"`
	AttackGap     int32                  `protobuf:"varint,7,opt,name=attack_gap,json=attackGap,proto3" json:"attack_gap,omitempty"`
	Sites         []*BossSite            `protobuf:"bytes,8,rep,name=sites,proto3" json:"sites,omitempty"`
	Version       int64                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossView) Reset() {
	*x = BossView{}
	mi := &file_battle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossView) ProtoMessage() {}

func (x *BossView) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossView.ProtoReflect.Descriptor instead.
func (*BossView) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{7}
}

func (x *BossView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BossView) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *BossView) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BossView) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *BossView) GetLastHit() string {
	if x != nil {
		return x.LastHit
	}
	return ""
}

func (x *BossView) GetRespawnIn() int32 {
	if x != nil {
		return x.RespawnIn
	}
	return 0
}

func (x *BossView) GetAttackGap() int32 {
	if x != nil {
		return x.AttackGap
	}
	return 0
}

func (x *BossView) GetSites() []*BossSite {
	if x != nil {
		return x.Sites
	}
	return nil
}

func (x *BossView) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type WorldState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Self           *PlayerView            `protobuf:"bytes,1,opt,name=self,proto3" json:"self,omitempty"`
	Map            *MapView               `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
	Maps           []*MapBrief            `protobuf:"bytes,3,rep,name=maps,proto3" json:"maps,omitempty"`
	Nodes          []*NodeView            `protobuf:"bytes,4,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Boss           *BossView              `protobuf:"bytes,5,opt,name=boss,proto3" json:"boss,omitempty"`
	Events         []string               `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	SessionVersion int64                  `protobuf:"varint,7,opt,name=session_version,json=sessionVersion,proto3" json:"session_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorldState) Reset() {
	*x = WorldState{}
	mi := &file_battle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldState) ProtoMessage() {}

func (x *WorldState) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldState.ProtoReflect.Descriptor instead.
func (*WorldState) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{8}
}

func (x *WorldState) GetSelf() *PlayerView {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *WorldState) GetMap() *MapView {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *WorldState) GetMaps() []*MapBrief {
	if x != nil {
		return x.Maps
	}
	return nil
}

func (x *WorldState) GetNodes() []*NodeView {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *WorldState) GetBoss() *BossView {
	if x != nil {
		return x.Boss
	}
	return nil
}

func (x *WorldState) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WorldState) GetSessionVersion() int64 {
	if x != nil {
		return x.SessionVersion
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Dir           string                 `protobuf:"bytes,5,opt,name=dir,proto3" json:"dir,omitempty"`
	MapId         string                 `protobuf:"bytes,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,7,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Confirm       string                 `protobuf:"bytes,8,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Item          string                 `protobuf:"bytes,9,opt,name=item,proto3" json:"item,omitempty"`
	Text          string                 `protobuf:"bytes,10,opt,name=text,proto3" json:"text,omitempty"`
	Ok            bool                   `protobuf:"varint,11,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	State         *WorldState            `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_battle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Message) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Message) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Message) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *Message) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *Message) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Message) GetConfirm() string {
	if x != nil {
		return x.Confirm
	}
	return ""
}

func (x *Message) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Message) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Message) GetState() *WorldState {
	if x != nil {
		return x.State
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	LastMap       string                 `protobuf:"bytes,3,opt,name=last_map,json=lastMap,proto3" json:"last_map,omitempty"`
	LastNode      string                 `protobuf:"bytes,4,opt,name=last_node,json=lastNode,proto3" json:"last_node,omitempty"`
	X             int32                  `protobuf:"varint,5,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,6,opt,name=y,proto3" json:"y,omitempty"`
	Hp            int32                  `protobuf:"varint,7,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int32                  `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Attack        int32                  `protobuf:"varint,9,opt,name=attack,proto3" json:"attack,omitempty"`
	Potions       int32                  `protobuf:"varint,10,opt,name=potions,proto3" json:"potions,omitempty"`
	Treasures     int32                  `protobuf:"varint,11,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Kills         int32                  `protobuf:"varint,12,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,13,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Victories     int32                  `protobuf:"varint,14,opt,name=victories,proto3" json:"victories,omitempty"`
	Alive         bool                   `protobuf:"varint,15,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_battle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{10}
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserProfile) GetLastMap() string {
	if x != nil {
		return x.LastMap
	}
	return ""
}

func (x *UserProfile) GetLastNode() string {
	if x != nil {
		return x.LastNode
	}
	return ""
}

func (x *UserProfile) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *UserProfile) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *UserProfile) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *UserProfile) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *UserProfile) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *UserProfile) GetPotions() int32 {
	if x != nil {
		return x.Potions
	}
	return 0
}

func (x *UserProfile) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *UserProfile) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *UserProfile) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *UserProfile) GetVictories() int32 {
	if x != nil {
		return x.Victories
	}
	return 0
}

func (x *UserProfile) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type AddPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPlayerReq) Reset() {
	*x = AddPlayerReq{}
	mi := &file_battle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayerReq) ProtoMessage() {}

func (x *AddPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayerReq.ProtoReflect.Descriptor instead.
func (*AddPlayerReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{11}
}

func (x *AddPlayerReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *AddPlayerReq) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type AddPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPlayerResp) Reset() {
	*x = AddPlayerResp{}
	mi := &file_battle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayerResp) ProtoMessage() {}

func (x *AddPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayerResp.ProtoReflect.Descriptor instead.
func (*AddPlayerResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{12}
}

func (x *AddPlayerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RemovePlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePlayerReq) Reset() {
	*x = RemovePlayerReq{}
	mi := &file_battle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlayerReq) ProtoMessage() {}

func (x *RemovePlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlayerReq.ProtoReflect.Descriptor instead.
func (*RemovePlayerReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{13}
}

func (x *RemovePlayerReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *RemovePlayerReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RemovePlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePlayerResp) Reset() {
	*x = RemovePlayerResp{}
	mi := &file_battle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlayerResp) ProtoMessage() {}

func (x *RemovePlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlayerResp.ProtoReflect.Descriptor instead.
func (*RemovePlayerResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{14}
}

func (x *RemovePlayerResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RemovePlayerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type MovePlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePlayerReq) Reset() {
	*x = MovePlayerReq{}
	mi := &file_battle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePlayerReq) ProtoMessage() {}

func (x *MovePlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePlayerReq.ProtoReflect.Descriptor instead.
func (*MovePlayerReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{15}
}

func (x *MovePlayerReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MovePlayerReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *MovePlayerReq) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type MovePlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovePlayerResp) Reset() {
	*x = MovePlayerResp{}
	mi := &file_battle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovePlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovePlayerResp) ProtoMessage() {}

func (x *MovePlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovePlayerResp.ProtoReflect.Descriptor instead.
func (*MovePlayerResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{16}
}

func (x *MovePlayerResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MovePlayerResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *MovePlayerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AttackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackReq) Reset() {
	*x = AttackReq{}
	mi := &file_battle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackReq) ProtoMessage() {}

func (x *AttackReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackReq.ProtoReflect.Descriptor instead.
func (*AttackReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{17}
}

func (x *AttackReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *AttackReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type AttackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	BLog          string                 `protobuf:"bytes,2,opt,name=b_log,json=bLog,proto3" json:"b_log,omitempty"`
	GmLog         string                 `protobuf:"bytes,3,opt,name=gm_log,json=gmLog,proto3" json:"gm_log,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,5,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttackResp) Reset() {
	*x = AttackResp{}
	mi := &file_battle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackResp) ProtoMessage() {}

func (x *AttackResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackResp.ProtoReflect.Descriptor instead.
func (*AttackResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{18}
}

func (x *AttackResp) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *AttackResp) GetBLog() string {
	if x != nil {
		return x.BLog
	}
	return ""
}

func (x *AttackResp) GetGmLog() string {
	if x != nil {
		return x.GmLog
	}
	return ""
}

func (x *AttackResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *AttackResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_battle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{19}
}

func (x *PingReq) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_battle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{20}
}

func (x *PingResp) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type BackgroundStepReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundStepReq) Reset() {
	*x = BackgroundStepReq{}
	mi := &file_battle_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundStepReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundStepReq) ProtoMessage() {}

func (x *BackgroundStepReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundStepReq.ProtoReflect.Descriptor instead.
func (*BackgroundStepReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{21}
}

type BackgroundStepResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*MapEvents           `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundStepResp) Reset() {
	*x = BackgroundStepResp{}
	mi := &file_battle_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundStepResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundStepResp) ProtoMessage() {}

func (x *BackgroundStepResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundStepResp.ProtoReflect.Descriptor instead.
func (*BackgroundStepResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{22}
}

func (x *BackgroundStepResp) GetEvents() []*MapEvents {
	if x != nil {
		return x.Events
	}
	return nil
}

type MapEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Events        []string               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapEvents) Reset() {
	*x = MapEvents{}
	mi := &file_battle_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapEvents) ProtoMessage() {}

func (x *MapEvents) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapEvents.ProtoReflect.Descriptor instead.
func (*MapEvents) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{23}
}

func (x *MapEvents) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapEvents) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type HealReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealReq) Reset() {
	*x = HealReq{}
	mi := &file_battle_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealReq) ProtoMessage() {}

func (x *HealReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealReq.ProtoReflect.Descriptor instead.
func (*HealReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{24}
}

func (x *HealReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *HealReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type HealResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealResp) Reset() {
	*x = HealResp{}
	mi := &file_battle_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealResp) ProtoMessage() {}

func (x *HealResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealResp.ProtoReflect.Descriptor instead.
func (*HealResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{25}
}

func (x *HealResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *HealResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *HealResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type BuyItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Item          string                 `protobuf:"bytes,3,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemReq) Reset() {
	*x = BuyItemReq{}
	mi := &file_battle_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemReq) ProtoMessage() {}

func (x *BuyItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemReq.ProtoReflect.Descriptor instead.
func (*BuyItemReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{26}
}

func (x *BuyItemReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *BuyItemReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BuyItemReq) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

type BuyItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyItemResp) Reset() {
	*x = BuyItemResp{}
	mi := &file_battle_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItemResp) ProtoMessage() {}

func (x *BuyItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItemResp.ProtoReflect.Descriptor instead.
func (*BuyItemResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{27}
}

func (x *BuyItemResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BuyItemResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *BuyItemResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileReq) Reset() {
	*x = ProfileReq{}
	mi := &file_battle_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileReq) ProtoMessage() {}

func (x *ProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileReq.ProtoReflect.Descriptor instead.
func (*ProfileReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{28}
}

func (x *ProfileReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *ProfileReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileResp) Reset() {
	*x = ProfileResp{}
	mi := &file_battle_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileResp) ProtoMessage() {}

func (x *ProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileResp.ProtoReflect.Descriptor instead.
func (*ProfileResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{29}
}

func (x *ProfileResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *ProfileResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RewardPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	TreasureDelta int32                  `protobuf:"varint,3,opt,name=treasure_delta,json=treasureDelta,proto3" json:"treasure_delta,omitempty"`
	VictoryDelta  int32                  `protobuf:"varint,4,opt,name=victory_delta,json=victoryDelta,proto3" json:"victory_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardPlayerReq) Reset() {
	*x = RewardPlayerReq{}
	mi := &file_battle_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardPlayerReq) ProtoMessage() {}

func (x *RewardPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardPlayerReq.ProtoReflect.Descriptor instead.
func (*RewardPlayerReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{30}
}

func (x *RewardPlayerReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *RewardPlayerReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RewardPlayerReq) GetTreasureDelta() int32 {
	if x != nil {
		return x.TreasureDelta
	}
	return 0
}

func (x *RewardPlayerReq) GetVictoryDelta() int32 {
	if x != nil {
		return x.VictoryDelta
	}
	return 0
}

type RewardPlayerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RewardPlayerResp) Reset() {
	*x = RewardPlayerResp{}
	mi := &file_battle_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RewardPlayerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RewardPlayerResp) ProtoMessage() {}

func (x *RewardPlayerResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RewardPlayerResp.ProtoReflect.Descriptor instead.
func (*RewardPlayerResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{31}
}

func (x *RewardPlayerResp) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *RewardPlayerResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SnapshotReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotReq) Reset() {
	*x = SnapshotReq{}
	mi := &file_battle_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotReq) ProtoMessage() {}

func (x *SnapshotReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotReq.ProtoReflect.Descriptor instead.
func (*SnapshotReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{32}
}

func (x *SnapshotReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

type SnapshotResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Map           *MapView               `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResp) Reset() {
	*x = SnapshotResp{}
	mi := &file_battle_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResp) ProtoMessage() {}

func (x *SnapshotResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResp.ProtoReflect.Descriptor instead.
func (*SnapshotResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{33}
}

func (x *SnapshotResp) GetMap() *MapView {
	if x != nil {
		return x.Map
	}
	return nil
}

type CountsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountsReq) Reset() {
	*x = CountsReq{}
	mi := &file_battle_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountsReq) ProtoMessage() {}

func (x *CountsReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountsReq.ProtoReflect.Descriptor instead.
func (*CountsReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{34}
}

func (x *CountsReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

type CountsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       int32                  `protobuf:"varint,1,opt,name=players,proto3" json:"players,omitempty"`
	Npcs          int32                  `protobuf:"varint,2,opt,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     int32                  `protobuf:"varint,3,opt,name=treasures,proto3" json:"treasures,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountsResp) Reset() {
	*x = CountsResp{}
	mi := &file_battle_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountsResp) ProtoMessage() {}

func (x *CountsResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountsResp.ProtoReflect.Descriptor instead.
func (*CountsResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{35}
}

func (x *CountsResp) GetPlayers() int32 {
	if x != nil {
		return x.Players
	}
	return 0
}

func (x *CountsResp) GetNpcs() int32 {
	if x != nil {
		return x.Npcs
	}
	return 0
}

func (x *CountsResp) GetTreasures() int32 {
	if x != nil {
		return x.Treasures
	}
	return 0
}

func (x *CountsResp) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CheckpointReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointReq) Reset() {
	*x = CheckpointReq{}
	mi := &file_battle_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointReq) ProtoMessage() {}

func (x *CheckpointReq) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointReq.ProtoReflect.Descriptor instead.
func (*CheckpointReq) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{36}
}

func (x *CheckpointReq) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

type CheckpointResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkpoint    *MapCheckpoint         `protobuf:"bytes,1,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResp) Reset() {
	*x = CheckpointResp{}
	mi := &file_battle_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResp) ProtoMessage() {}

func (x *CheckpointResp) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResp.ProtoReflect.Descriptor instead.
func (*CheckpointResp) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{37}
}

func (x *CheckpointResp) GetCheckpoint() *MapCheckpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type MapCheckpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MapId         string                 `protobuf:"bytes,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Terrain       []string               `protobuf:"bytes,4,rep,name=terrain,proto3" json:"terrain,omitempty"`
	Players       []*PlayerView          `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	Npcs          []*NPCView             `protobuf:"bytes,6,rep,name=npcs,proto3" json:"npcs,omitempty"`
	Treasures     []*TreasureView        `protobuf:"bytes,7,rep,name=treasures,proto3" json:"treasures,omitempty"`
	Checkpoint    string                 `protobuf:"bytes,8,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapCheckpoint) Reset() {
	*x = MapCheckpoint{}
	mi := &file_battle_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapCheckpoint) ProtoMessage() {}

func (x *MapCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_battle_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapCheckpoint.ProtoReflect.Descriptor instead.
func (*MapCheckpoint) Descriptor() ([]byte, []int) {
	return file_battle_proto_rawDescGZIP(), []int{38}
}

func (x *MapCheckpoint) GetMapId() string {
	if x != nil {
		return x.MapId
	}
	return ""
}

func (x *MapCheckpoint) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MapCheckpoint) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MapCheckpoint) GetTerrain() []string {
	if x != nil {
		return x.Terrain
	}
	return nil
}

func (x *MapCheckpoint) GetPlayers() []*PlayerView {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *MapCheckpoint) GetNpcs() []*NPCView {
	if x != nil {
		return x.Npcs
	}
	return nil
}

func (x *MapCheckpoint) GetTreasures() []*TreasureView {
	if x != nil {
		return x.Treasures
	}
	return nil
}

func (x *MapCheckpoint) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

var File_battle_proto protoreflect.FileDescriptor

const file_battle_proto_rawDesc = "" +
	"\n" +
	"\fbattle.proto\x12\x02pb\"\xf4\x02\n" +
	"\n" +
	"PlayerView\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x15\n" +
	"\x06map_id\x18\x02 \x01(\tR\x05mapId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\a \x01(\x05R\x06attack\x12\x18\n" +
	"\apotions\x18\b \x01(\x05R\apotions\x12\x1c\n" +
	"\ttreasures\x18\t \x01(\x05R\ttreasures\x12\x14\n" +
	"\x05kills\x18\n" +
	" \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\v \x01(\x05R\x06deaths\x12\x1c\n" +
	"\tvictories\x18\f \x01(\x05R\tvictories\x12\x14\n" +
	"\x05alive\x18\r \x01(\bR\x05alive\x12\x1d\n" +
	"\n" +
	"respawn_in\x18\x0e \x01(\x05R\trespawnIn\x12\x1f\n" +
	"\vlast_update\x18\x0f \x01(\tR\n" +
	"lastUpdate\"\x9e\x01\n" +
	"\aNPCView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\a \x01(\x05R\x06attack\x12\x14\n" +
	"\x05alive\x18\b \x01(\bR\x05alive\"d\n" +
	"\fTreasureView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x05R\x05value\"\x86\x02\n" +
	"\bMapBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aplayers\x18\x04 \x01(\x05R\aplayers\x12\x12\n" +
	"\x04npcs\x18\x05 \x01(\x05R\x04npcs\x12\x1c\n" +
	"\ttreasures\x18\x06 \x01(\x05R\ttreasures\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x18\n" +
	"\aprimary\x18\b \x01(\bR\aprimary\x12\x1d\n" +
	"\n" +
	"is_current\x18\t \x01(\bR\tisCurrent\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\n" +
	" \x01(\x03R\n" +
	"checkpoint\"\xb5\x01\n" +
	"\bNodeView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12!\n" +
	"\fprimary_maps\x18\x04 \x03(\tR\vprimaryMaps\x12!\n" +
	"\freplica_maps\x18\x05 \x03(\tR\vreplicaMaps\x12%\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\tR\rlastHeartbeat\"\xa3\x02\n" +
	"\aMapView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x18\n" +
	"\aterrain\x18\x06 \x03(\tR\aterrain\x12(\n" +
	"\aplayers\x18\a \x03(\v2\x0e.pb.PlayerViewR\aplayers\x12\x1f\n" +
	"\x04npcs\x18\b \x03(\v2\v.pb.NPCViewR\x04npcs\x12.\n" +
	"\ttreasures\x18\t \x03(\v2\x10.pb.TreasureViewR\ttreasures\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\"=\n" +
	"\bBossSite\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\xf2\x01\n" +
	"\bBossView\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02hp\x18\x02 \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x03 \x01(\x05R\x05maxHp\x12\x14\n" +
	"\x05alive\x18\x04 \x01(\bR\x05alive\x12\x19\n" +
	"\blast_hit\x18\x05 \x01(\tR\alastHit\x12\x1d\n" +
	"\n" +
	"respawn_in\x18\x06 \x01(\x05R\trespawnIn\x12\x1d\n" +
	"\n" +
	"attack_gap\x18\a \x01(\x05R\tattackGap\x12\"\n" +
	"\x05sites\x18\b \x03(\v2\f.pb.BossSiteR\x05sites\x12\x18\n" +
	"\aversion\x18\t \x01(\x03R\aversion\"\xf8\x01\n" +
	"\n" +
	"WorldState\x12\"\n" +
	"\x04self\x18\x01 \x01(\v2\x0e.pb.PlayerViewR\x04self\x12\x1d\n" +
	"\x03map\x18\x02 \x01(\v2\v.pb.MapViewR\x03map\x12 \n" +
	"\x04maps\x18\x03 \x03(\v2\f.pb.MapBriefR\x04maps\x12\"\n" +
	"\x05nodes\x18\x04 \x03(\v2\f.pb.NodeViewR\x05nodes\x12 \n" +
	"\x04boss\x18\x05 \x01(\v2\f.pb.BossViewR\x04boss\x12\x16\n" +
	"\x06events\x18\x06 \x03(\tR\x06events\x12'\n" +
	"\x0fsession_version\x18\a \x01(\x03R\x0esessionVersion\"\xbd\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x10\n" +
	"\x03dir\x18\x05 \x01(\tR\x03dir\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\tR\x05mapId\x12\x17\n" +
	"\anode_id\x18\a \x01(\tR\x06nodeId\x12\x18\n" +
	"\aconfirm\x18\b \x01(\tR\aconfirm\x12\x12\n" +
	"\x04item\x18\t \x01(\tR\x04item\x12\x12\n" +
	"\x04text\x18\n" +
	" \x01(\tR\x04text\x12\x0e\n" +
	"\x02ok\x18\v \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12$\n" +
	"\x05state\x18\r \x01(\v2\x0e.pb.WorldStateR\x05state\"\xfb\x02\n" +
	"\vUserProfile\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x19\n" +
	"\blast_map\x18\x03 \x01(\tR\alastMap\x12\x1b\n" +
	"\tlast_node\x18\x04 \x01(\tR\blastNode\x12\f\n" +
	"\x01x\x18\x05 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x06 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02hp\x18\a \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\x05R\x05maxHp\x12\x16\n" +
	"\x06attack\x18\t \x01(\x05R\x06attack\x12\x18\n" +
	"\apotions\x18\n" +
	" \x01(\x05R\apotions\x12\x1c\n" +
	"\ttreasures\x18\v \x01(\x05R\ttreasures\x12\x14\n" +
	"\x05kills\x18\f \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\r \x01(\x05R\x06deaths\x12\x1c\n" +
	"\tvictories\x18\x0e \x01(\x05R\tvictories\x12\x14\n" +
	"\x05alive\x18\x0f \x01(\bR\x05alive\"P\n" +
	"\fAddPlayerReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12)\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.pb.UserProfileR\aprofile\"\x1f\n" +
	"\rAddPlayerResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"D\n" +
	"\x0fRemovePlayerReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"M\n" +
	"\x10RemovePlayerResp\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"T\n" +
	"\rMovePlayerReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\"_\n" +
	"\x0eMovePlayerResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12)\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\">\n" +
	"\tAttackReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x85\x01\n" +
	"\n" +
	"AttackResp\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\x12\x13\n" +
	"\x05b_log\x18\x02 \x01(\tR\x04bLog\x12\x15\n" +
	"\x06gm_log\x18\x03 \x01(\tR\x05gmLog\x12)\n" +
	"\aprofile\x18\x04 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x05 \x01(\bR\x02ok\"\"\n" +
	"\aPingReq\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x1a\n" +
	"\bPingResp\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\"\x13\n" +
	"\x11BackgroundStepReq\";\n" +
	"\x12BackgroundStepResp\x12%\n" +
	"\x06events\x18\x01 \x03(\v2\r.pb.MapEventsR\x06events\":\n" +
	"\tMapEvents\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\"<\n" +
	"\aHealReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"Y\n" +
	"\bHealResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12)\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"S\n" +
	"\n" +
	"BuyItemReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x12\n" +
	"\x04item\x18\x03 \x01(\tR\x04item\"\\\n" +
	"\vBuyItemResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12)\n" +
	"\aprofile\x18\x02 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\"?\n" +
	"\n" +
	"ProfileReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"H\n" +
	"\vProfileResp\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x90\x01\n" +
	"\x0fRewardPlayerReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12%\n" +
	"\x0etreasure_delta\x18\x03 \x01(\x05R\rtreasureDelta\x12#\n" +
	"\rvictory_delta\x18\x04 \x01(\x05R\fvictoryDelta\"M\n" +
	"\x10RewardPlayerResp\x12)\n" +
	"\aprofile\x18\x01 \x01(\v2\x0f.pb.UserProfileR\aprofile\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"$\n" +
	"\vSnapshotReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\"-\n" +
	"\fSnapshotResp\x12\x1d\n" +
	"\x03map\x18\x01 \x01(\v2\v.pb.MapViewR\x03map\"\"\n" +
	"\tCountsReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\"r\n" +
	"\n" +
	"CountsResp\x12\x18\n" +
	"\aplayers\x18\x01 \x01(\x05R\aplayers\x12\x12\n" +
	"\x04npcs\x18\x02 \x01(\x05R\x04npcs\x12\x1c\n" +
	"\ttreasures\x18\x03 \x01(\x05R\ttreasures\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\"&\n" +
	"\rCheckpointReq\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\"C\n" +
	"\x0eCheckpointResp\x121\n" +
	"\n" +
	"checkpoint\x18\x01 \x01(\v2\x11.pb.MapCheckpointR\n" +
	"checkpoint\"\x8e\x02\n" +
	"\rMapCheckpoint\x12\x15\n" +
	"\x06map_id\x18\x01 \x01(\tR\x05mapId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x18\n" +
	"\aterrain\x18\x04 \x03(\tR\aterrain\x12(\n" +
	"\aplayers\x18\x05 \x03(\v2\x0e.pb.PlayerViewR\aplayers\x12\x1f\n" +
	"\x04npcs\x18\x06 \x03(\v2\v.pb.NPCViewR\x04npcs\x12.\n" +
	"\ttreasures\x18\a \x03(\v2\x10.pb.TreasureViewR\ttreasures\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\b \x01(\tR\n" +
	"checkpoint2<\n" +
	"\x0eGatewayService\x12*\n" +
	"\n" +
	"GameStream\x12\v.pb.Message\x1a\v.pb.Message(\x010\x012\xff\x04\n" +
	"\vNodeService\x12!\n" +
	"\x04Ping\x12\v.pb.PingReq\x1a\f.pb.PingResp\x120\n" +
	"\tAddPlayer\x12\x10.pb.AddPlayerReq\x1a\x11.pb.AddPlayerResp\x129\n" +
	"\fRemovePlayer\x12\x13.pb.RemovePlayerReq\x1a\x14.pb.RemovePlayerResp\x123\n" +
	"\n" +
	"MovePlayer\x12\x11.pb.MovePlayerReq\x1a\x12.pb.MovePlayerResp\x12'\n" +
	"\x06Attack\x12\r.pb.AttackReq\x1a\x0e.pb.AttackResp\x12!\n" +
	"\x04Heal\x12\v.pb.HealReq\x1a\f.pb.HealResp\x12*\n" +
	"\aBuyItem\x12\x0e.pb.BuyItemReq\x1a\x0f.pb.BuyItemResp\x12*\n" +
	"\aProfile\x12\x0e.pb.ProfileReq\x1a\x0f.pb.ProfileResp\x129\n" +
	"\fRewardPlayer\x12\x13.pb.RewardPlayerReq\x1a\x14.pb.RewardPlayerResp\x12-\n" +
	"\bSnapshot\x12\x0f.pb.SnapshotReq\x1a\x10.pb.SnapshotResp\x12'\n" +
	"\x06Counts\x12\r.pb.CountsReq\x1a\x0e.pb.CountsResp\x123\n" +
	"\n" +
	"Checkpoint\x12\x11.pb.CheckpointReq\x1a\x12.pb.CheckpointResp\x12?\n" +
	"\x0eBackgroundStep\x12\x15.pb.BackgroundStepReq\x1a\x16.pb.BackgroundStepRespB\x10Z\x0ebattleworld/pbb\x06proto3"

var (
	file_battle_proto_rawDescOnce sync.Once
	file_battle_proto_rawDescData []byte
)

func file_battle_proto_rawDescGZIP() []byte {
	file_battle_proto_rawDescOnce.Do(func() {
		file_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)))
	})
	return file_battle_proto_rawDescData
}

var file_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_battle_proto_goTypes = []any{
	(*PlayerView)(nil),         // 0: pb.PlayerView
	(*NPCView)(nil),            // 1: pb.NPCView
	(*TreasureView)(nil),       // 2: pb.TreasureView
	(*MapBrief)(nil),           // 3: pb.MapBrief
	(*NodeView)(nil),           // 4: pb.NodeView
	(*MapView)(nil),            // 5: pb.MapView
	(*BossSite)(nil),           // 6: pb.BossSite
	(*BossView)(nil),           // 7: pb.BossView
	(*WorldState)(nil),         // 8: pb.WorldState
	(*Message)(nil),            // 9: pb.Message
	(*UserProfile)(nil),        // 10: pb.UserProfile
	(*AddPlayerReq)(nil),       // 11: pb.AddPlayerReq
	(*AddPlayerResp)(nil),      // 12: pb.AddPlayerResp
	(*RemovePlayerReq)(nil),    // 13: pb.RemovePlayerReq
	(*RemovePlayerResp)(nil),   // 14: pb.RemovePlayerResp
	(*MovePlayerReq)(nil),      // 15: pb.MovePlayerReq
	(*MovePlayerResp)(nil),     // 16: pb.MovePlayerResp
	(*AttackReq)(nil),          // 17: pb.AttackReq
	(*AttackResp)(nil),         // 18: pb.AttackResp
	(*PingReq)(nil),            // 19: pb.PingReq
	(*PingResp)(nil),           // 20: pb.PingResp
	(*BackgroundStepReq)(nil),  // 21: pb.BackgroundStepReq
	(*BackgroundStepResp)(nil), // 22: pb.BackgroundStepResp
	(*MapEvents)(nil),          // 23: pb.MapEvents
	(*HealReq)(nil),            // 24: pb.HealReq
	(*HealResp)(nil),           // 25: pb.HealResp
	(*BuyItemReq)(nil),         // 26: pb.BuyItemReq
	(*BuyItemResp)(nil),        // 27: pb.BuyItemResp
	(*ProfileReq)(nil),         // 28: pb.ProfileReq
	(*ProfileResp)(nil),        // 29: pb.ProfileResp
	(*RewardPlayerReq)(nil),    // 30: pb.RewardPlayerReq
	(*RewardPlayerResp)(nil),   // 31: pb.RewardPlayerResp
	(*SnapshotReq)(nil),        // 32: pb.SnapshotReq
	(*SnapshotResp)(nil),       // 33: pb.SnapshotResp
	(*CountsReq)(nil),          // 34: pb.CountsReq
	(*CountsResp)(nil),         // 35: pb.CountsResp
	(*CheckpointReq)(nil),      // 36: pb.CheckpointReq
	(*CheckpointResp)(nil),     // 37: pb.CheckpointResp
	(*MapCheckpoint)(nil),      // 38: pb.MapCheckpoint
}
var file_battle_proto_depIdxs = []int32{
	0,  // 0: pb.MapView.players:type_name -> pb.PlayerView
	1,  // 1: pb.MapView.npcs:type_name -> pb.NPCView
	2,  // 2: pb.MapView.treasures:type_name -> pb.TreasureView
	6,  // 3: pb.BossView.sites:type_name -> pb.BossSite
	0,  // 4: pb.WorldState.self:type_name -> pb.PlayerView
	5,  // 5: pb.WorldState.map:type_name -> pb.MapView
	3,  // 6: pb.WorldState.maps:type_name -> pb.MapBrief
	4,  // 7: pb.WorldState.nodes:type_name -> pb.NodeView
	7,  // 8: pb.WorldState.boss:type_name -> pb.BossView
	8,  // 9: pb.Message.state:type_name -> pb.WorldState
	10, // 10: pb.AddPlayerReq.profile:type_name -> pb.UserProfile
	10, // 11: pb.RemovePlayerResp.profile:type_name -> pb.UserProfile
	10, // 12: pb.MovePlayerResp.profile:type_name -> pb.UserProfile
	10, // 13: pb.AttackResp.profile:type_name -> pb.UserProfile
	23, // 14: pb.BackgroundStepResp.events:type_name -> pb.MapEvents
	10, // 15: pb.HealResp.profile:type_name -> pb.UserProfile
	10, // 16: pb.BuyItemResp.profile:type_name -> pb.UserProfile
	10, // 17: pb.ProfileResp.profile:type_name -> pb.UserProfile
	10, // 18: pb.RewardPlayerResp.profile:type_name -> pb.UserProfile
	5,  // 19: pb.SnapshotResp.map:type_name -> pb.MapView
	38, // 20: pb.CheckpointResp.checkpoint:type_name -> pb.MapCheckpoint
	0,  // 21: pb.MapCheckpoint.players:type_name -> pb.PlayerView
	1,  // 22: pb.MapCheckpoint.npcs:type_name -> pb.NPCView
	2,  // 23: pb.MapCheckpoint.treasures:type_name -> pb.TreasureView
	9,  // 24: pb.GatewayService.GameStream:input_type -> pb.Message
	19, // 25: pb.NodeService.Ping:input_type -> pb.PingReq
	11, // 26: pb.NodeService.AddPlayer:input_type -> pb.AddPlayerReq
	13, // 27: pb.NodeService.RemovePlayer:input_type -> pb.RemovePlayerReq
	15, // 28: pb.NodeService.MovePlayer:input_type -> pb.MovePlayerReq
	17, // 29: pb.NodeService.Attack:input_type -> pb.AttackReq
	24, // 30: pb.NodeService.Heal:input_type -> pb.HealReq
	26, // 31: pb.NodeService.BuyItem:input_type -> pb.BuyItemReq
	28, // 32: pb.NodeService.Profile:input_type -> pb.ProfileReq
	30, // 33: pb.NodeService.RewardPlayer:input_type -> pb.RewardPlayerReq
	32, // 34: pb.NodeService.Snapshot:input_type -> pb.SnapshotReq
	34, // 35: pb.NodeService.Counts:input_type -> pb.CountsReq
	36, // 36: pb.NodeService.Checkpoint:input_type -> pb.CheckpointReq
	21, // 37: pb.NodeService.BackgroundStep:input_type -> pb.BackgroundStepReq
	9,  // 38: pb.GatewayService.GameStream:output_type -> pb.Message
	20, // 39: pb.NodeService.Ping:output_type -> pb.PingResp
	12, // 40: pb.NodeService.AddPlayer:output_type -> pb.AddPlayerResp
	14, // 41: pb.NodeService.RemovePlayer:output_type -> pb.RemovePlayerResp
	16, // 42: pb.NodeService.MovePlayer:output_type -> pb.MovePlayerResp
	18, // 43: pb.NodeService.Attack:output_type -> pb.AttackResp
	25, // 44: pb.NodeService.Heal:output_type -> pb.HealResp
	27, // 45: pb.NodeService.BuyItem:output_type -> pb.BuyItemResp
	29, // 46: pb.NodeService.Profile:output_type -> pb.ProfileResp
	31, // 47: pb.NodeService.RewardPlayer:output_type -> pb.RewardPlayerResp
	33, // 48: pb.NodeService.Snapshot:output_type -> pb.SnapshotResp
	35, // 49: pb.NodeService.Counts:output_type -> pb.CountsResp
	37, // 50: pb.NodeService.Checkpoint:output_type -> pb.CheckpointResp
	22, // 51: pb.NodeService.BackgroundStep:output_type -> pb.BackgroundStepResp
	38, // [38:52] is the sub-list for method output_type
	24, // [24:38] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_battle_proto_init() }
func file_battle_proto_init() {
	if File_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_battle_proto_rawDesc), len(file_battle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_battle_proto_goTypes,
		DependencyIndexes: file_battle_proto_depIdxs,
		MessageInfos:      file_battle_proto_msgTypes,
	}.Build()
	File_battle_proto = out.File
	file_battle_proto_goTypes = nil
	file_battle_proto_depIdxs = nil
}
