// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.1
// source: pb/battle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GameStream_FullMethodName = "/pb.GatewayService/GameStream"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService exposes the typed bidirectional game stream.
type GatewayServiceClient interface {
	GameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEnvelope, ServerEnvelope], error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GameStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEnvelope, ServerEnvelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_GameStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientEnvelope, ServerEnvelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_GameStreamClient = grpc.BidiStreamingClient[ClientEnvelope, ServerEnvelope]

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService exposes the typed bidirectional game stream.
type GatewayServiceServer interface {
	GameStream(grpc.BidiStreamingServer[ClientEnvelope, ServerEnvelope]) error
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GameStream(grpc.BidiStreamingServer[ClientEnvelope, ServerEnvelope]) error {
	return status.Errorf(codes.Unimplemented, "method GameStream not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GameStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServiceServer).GameStream(&grpc.GenericServerStream[ClientEnvelope, ServerEnvelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_GameStreamServer = grpc.BidiStreamingServer[ClientEnvelope, ServerEnvelope]

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GameStream",
			Handler:       _GatewayService_GameStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/battle.proto",
}

const (
	AdminService_GetGatewayStatus_FullMethodName = "/pb.AdminService/GetGatewayStatus"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService is intentionally separate from player streams. It can evolve its
// authorization independently and never needs a synthetic player authentication frame.
type AdminServiceClient interface {
	GetGatewayStatus(ctx context.Context, in *GatewayStatusRequest, opts ...grpc.CallOption) (*GatewayStatusResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) GetGatewayStatus(ctx context.Context, in *GatewayStatusRequest, opts ...grpc.CallOption) (*GatewayStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GatewayStatusResponse)
	err := c.cc.Invoke(ctx, AdminService_GetGatewayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService is intentionally separate from player streams. It can evolve its
// authorization independently and never needs a synthetic player authentication frame.
type AdminServiceServer interface {
	GetGatewayStatus(context.Context, *GatewayStatusRequest) (*GatewayStatusResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) GetGatewayStatus(context.Context, *GatewayStatusRequest) (*GatewayStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayStatus not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_GetGatewayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetGatewayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetGatewayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetGatewayStatus(ctx, req.(*GatewayStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGatewayStatus",
			Handler:    _AdminService_GetGatewayStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/battle.proto",
}

const (
	NodeService_Ping_FullMethodName         = "/pb.NodeService/Ping"
	NodeService_AddPlayer_FullMethodName    = "/pb.NodeService/AddPlayer"
	NodeService_RemovePlayer_FullMethodName = "/pb.NodeService/RemovePlayer"
	NodeService_MovePlayer_FullMethodName   = "/pb.NodeService/MovePlayer"
	NodeService_Attack_FullMethodName       = "/pb.NodeService/Attack"
	NodeService_Heal_FullMethodName         = "/pb.NodeService/Heal"
	NodeService_BuyItem_FullMethodName      = "/pb.NodeService/BuyItem"
	NodeService_AttackBoss_FullMethodName   = "/pb.NodeService/AttackBoss"
	NodeService_Profile_FullMethodName      = "/pb.NodeService/Profile"
	NodeService_RewardPlayer_FullMethodName = "/pb.NodeService/RewardPlayer"
	NodeService_Snapshot_FullMethodName     = "/pb.NodeService/Snapshot"
	NodeService_Counts_FullMethodName       = "/pb.NodeService/Counts"
	NodeService_Checkpoint_FullMethodName   = "/pb.NodeService/Checkpoint"
	NodeService_Promote_FullMethodName      = "/pb.NodeService/Promote"
	NodeService_View_FullMethodName         = "/pb.NodeService/View"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService is the typed Node RPC contract used by Gateway and Coordinator.
// Every map mutation carries MapAuthority so the node can fence stale owners before
// world state changes; no Node data-plane payload includes an account password hash.
type NodeServiceClient interface {
	Ping(ctx context.Context, in *NodePingRequest, opts ...grpc.CallOption) (*NodePingResponse, error)
	AddPlayer(ctx context.Context, in *NodeAddPlayerRequest, opts ...grpc.CallOption) (*NodeAddPlayerResponse, error)
	RemovePlayer(ctx context.Context, in *NodeRemovePlayerRequest, opts ...grpc.CallOption) (*NodeRemovePlayerResponse, error)
	MovePlayer(ctx context.Context, in *NodeMovePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error)
	Attack(ctx context.Context, in *NodeAttackRequest, opts ...grpc.CallOption) (*NodeAttackResponse, error)
	Heal(ctx context.Context, in *NodePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error)
	BuyItem(ctx context.Context, in *NodeBuyItemRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error)
	AttackBoss(ctx context.Context, in *NodePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error)
	Profile(ctx context.Context, in *NodeProfileRequest, opts ...grpc.CallOption) (*NodeProfileResponse, error)
	RewardPlayer(ctx context.Context, in *NodeRewardPlayerRequest, opts ...grpc.CallOption) (*NodeProfileResponse, error)
	Snapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*NodeSnapshotResponse, error)
	Counts(ctx context.Context, in *NodeCountsRequest, opts ...grpc.CallOption) (*NodeCountsResponse, error)
	Checkpoint(ctx context.Context, in *NodeCheckpointRequest, opts ...grpc.CallOption) (*NodeCheckpointResponse, error)
	Promote(ctx context.Context, in *NodePromoteRequest, opts ...grpc.CallOption) (*NodePromoteResponse, error)
	View(ctx context.Context, in *NodeViewRequest, opts ...grpc.CallOption) (*NodeViewResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Ping(ctx context.Context, in *NodePingRequest, opts ...grpc.CallOption) (*NodePingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePingResponse)
	err := c.cc.Invoke(ctx, NodeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddPlayer(ctx context.Context, in *NodeAddPlayerRequest, opts ...grpc.CallOption) (*NodeAddPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeAddPlayerResponse)
	err := c.cc.Invoke(ctx, NodeService_AddPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemovePlayer(ctx context.Context, in *NodeRemovePlayerRequest, opts ...grpc.CallOption) (*NodeRemovePlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRemovePlayerResponse)
	err := c.cc.Invoke(ctx, NodeService_RemovePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) MovePlayer(ctx context.Context, in *NodeMovePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePlayerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_MovePlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Attack(ctx context.Context, in *NodeAttackRequest, opts ...grpc.CallOption) (*NodeAttackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeAttackResponse)
	err := c.cc.Invoke(ctx, NodeService_Attack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Heal(ctx context.Context, in *NodePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePlayerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_Heal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) BuyItem(ctx context.Context, in *NodeBuyItemRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePlayerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_BuyItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AttackBoss(ctx context.Context, in *NodePlayerRequest, opts ...grpc.CallOption) (*NodePlayerActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePlayerActionResponse)
	err := c.cc.Invoke(ctx, NodeService_AttackBoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Profile(ctx context.Context, in *NodeProfileRequest, opts ...grpc.CallOption) (*NodeProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeProfileResponse)
	err := c.cc.Invoke(ctx, NodeService_Profile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RewardPlayer(ctx context.Context, in *NodeRewardPlayerRequest, opts ...grpc.CallOption) (*NodeProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeProfileResponse)
	err := c.cc.Invoke(ctx, NodeService_RewardPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Snapshot(ctx context.Context, in *NodeSnapshotRequest, opts ...grpc.CallOption) (*NodeSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Counts(ctx context.Context, in *NodeCountsRequest, opts ...grpc.CallOption) (*NodeCountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeCountsResponse)
	err := c.cc.Invoke(ctx, NodeService_Counts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Checkpoint(ctx context.Context, in *NodeCheckpointRequest, opts ...grpc.CallOption) (*NodeCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeCheckpointResponse)
	err := c.cc.Invoke(ctx, NodeService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) Promote(ctx context.Context, in *NodePromoteRequest, opts ...grpc.CallOption) (*NodePromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodePromoteResponse)
	err := c.cc.Invoke(ctx, NodeService_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) View(ctx context.Context, in *NodeViewRequest, opts ...grpc.CallOption) (*NodeViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeViewResponse)
	err := c.cc.Invoke(ctx, NodeService_View_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService is the typed Node RPC contract used by Gateway and Coordinator.
// Every map mutation carries MapAuthority so the node can fence stale owners before
// world state changes; no Node data-plane payload includes an account password hash.
type NodeServiceServer interface {
	Ping(context.Context, *NodePingRequest) (*NodePingResponse, error)
	AddPlayer(context.Context, *NodeAddPlayerRequest) (*NodeAddPlayerResponse, error)
	RemovePlayer(context.Context, *NodeRemovePlayerRequest) (*NodeRemovePlayerResponse, error)
	MovePlayer(context.Context, *NodeMovePlayerRequest) (*NodePlayerActionResponse, error)
	Attack(context.Context, *NodeAttackRequest) (*NodeAttackResponse, error)
	Heal(context.Context, *NodePlayerRequest) (*NodePlayerActionResponse, error)
	BuyItem(context.Context, *NodeBuyItemRequest) (*NodePlayerActionResponse, error)
	AttackBoss(context.Context, *NodePlayerRequest) (*NodePlayerActionResponse, error)
	Profile(context.Context, *NodeProfileRequest) (*NodeProfileResponse, error)
	RewardPlayer(context.Context, *NodeRewardPlayerRequest) (*NodeProfileResponse, error)
	Snapshot(context.Context, *NodeSnapshotRequest) (*NodeSnapshotResponse, error)
	Counts(context.Context, *NodeCountsRequest) (*NodeCountsResponse, error)
	Checkpoint(context.Context, *NodeCheckpointRequest) (*NodeCheckpointResponse, error)
	Promote(context.Context, *NodePromoteRequest) (*NodePromoteResponse, error)
	View(context.Context, *NodeViewRequest) (*NodeViewResponse, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) Ping(context.Context, *NodePingRequest) (*NodePingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeServiceServer) AddPlayer(context.Context, *NodeAddPlayerRequest) (*NodeAddPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlayer not implemented")
}
func (UnimplementedNodeServiceServer) RemovePlayer(context.Context, *NodeRemovePlayerRequest) (*NodeRemovePlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePlayer not implemented")
}
func (UnimplementedNodeServiceServer) MovePlayer(context.Context, *NodeMovePlayerRequest) (*NodePlayerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MovePlayer not implemented")
}
func (UnimplementedNodeServiceServer) Attack(context.Context, *NodeAttackRequest) (*NodeAttackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Attack not implemented")
}
func (UnimplementedNodeServiceServer) Heal(context.Context, *NodePlayerRequest) (*NodePlayerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heal not implemented")
}
func (UnimplementedNodeServiceServer) BuyItem(context.Context, *NodeBuyItemRequest) (*NodePlayerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyItem not implemented")
}
func (UnimplementedNodeServiceServer) AttackBoss(context.Context, *NodePlayerRequest) (*NodePlayerActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttackBoss not implemented")
}
func (UnimplementedNodeServiceServer) Profile(context.Context, *NodeProfileRequest) (*NodeProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Profile not implemented")
}
func (UnimplementedNodeServiceServer) RewardPlayer(context.Context, *NodeRewardPlayerRequest) (*NodeProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardPlayer not implemented")
}
func (UnimplementedNodeServiceServer) Snapshot(context.Context, *NodeSnapshotRequest) (*NodeSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedNodeServiceServer) Counts(context.Context, *NodeCountsRequest) (*NodeCountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Counts not implemented")
}
func (UnimplementedNodeServiceServer) Checkpoint(context.Context, *NodeCheckpointRequest) (*NodeCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedNodeServiceServer) Promote(context.Context, *NodePromoteRequest) (*NodePromoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedNodeServiceServer) View(context.Context, *NodeViewRequest) (*NodeViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}
func (UnimplementedNodeServiceServer) testEmbeddedByValue()                     {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Ping(ctx, req.(*NodePingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AddPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddPlayer(ctx, req.(*NodeAddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRemovePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RemovePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemovePlayer(ctx, req.(*NodeRemovePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_MovePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMovePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).MovePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_MovePlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).MovePlayer(ctx, req.(*NodeMovePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Attack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAttackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Attack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Attack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Attack(ctx, req.(*NodeAttackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Heal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Heal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Heal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Heal(ctx, req.(*NodePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_BuyItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeBuyItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).BuyItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_BuyItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).BuyItem(ctx, req.(*NodeBuyItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AttackBoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AttackBoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_AttackBoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AttackBoss(ctx, req.(*NodePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Profile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Profile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Profile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Profile(ctx, req.(*NodeProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RewardPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRewardPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RewardPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_RewardPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RewardPlayer(ctx, req.(*NodeRewardPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Snapshot(ctx, req.(*NodeSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Counts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Counts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Counts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Counts(ctx, req.(*NodeCountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Checkpoint(ctx, req.(*NodeCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodePromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Promote(ctx, req.(*NodePromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).View(ctx, req.(*NodeViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _NodeService_Ping_Handler,
		},
		{
			MethodName: "AddPlayer",
			Handler:    _NodeService_AddPlayer_Handler,
		},
		{
			MethodName: "RemovePlayer",
			Handler:    _NodeService_RemovePlayer_Handler,
		},
		{
			MethodName: "MovePlayer",
			Handler:    _NodeService_MovePlayer_Handler,
		},
		{
			MethodName: "Attack",
			Handler:    _NodeService_Attack_Handler,
		},
		{
			MethodName: "Heal",
			Handler:    _NodeService_Heal_Handler,
		},
		{
			MethodName: "BuyItem",
			Handler:    _NodeService_BuyItem_Handler,
		},
		{
			MethodName: "AttackBoss",
			Handler:    _NodeService_AttackBoss_Handler,
		},
		{
			MethodName: "Profile",
			Handler:    _NodeService_Profile_Handler,
		},
		{
			MethodName: "RewardPlayer",
			Handler:    _NodeService_RewardPlayer_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _NodeService_Snapshot_Handler,
		},
		{
			MethodName: "Counts",
			Handler:    _NodeService_Counts_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _NodeService_Checkpoint_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _NodeService_Promote_Handler,
		},
		{
			MethodName: "View",
			Handler:    _NodeService_View_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/battle.proto",
}
